spring:
  application:
    name: spot-spread
  datasource:
    url: jdbc:mysql://localhost:3306/spot_spread?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8088

cors:
  allowed-origins: http://localhost:8080,http://127.0.0.1:8080

influxdb:
  url: http://localhost:8086
  token: ${INFLUXDB_TOKEN:oNMW7Fg5Myir9EXQoBN9KOfphszENQ-Zq6PcaG5-d-ohSFvP12Bgl_EEdCUsAxPMi3eGPQ6CpLB4mMDZ1u9cdg==}
  org: ${INFLUXDB_ORG:spot-spread}
  bucket: ${INFLUXDB_BUCKET:spot-spread}
  enabled: ${INFLUXDB_ENABLED:true}

arbitrage:
  profit-mode: ${ARBITRAGE_PROFIT_MODE:taker-taker}  # 可选: max-profit, taker-maker, taker-taker
