spring:
  application:
    name: spot-spread
  datasource:
    url: jdbc:mysql://localhost:3306/spot_spread?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8088

cors:
  allowed-origins: http://localhost:8080,http://127.0.0.1:8080
